name: "Mentra China Cloud Deployment"
description: "Build, push and deploy to Alibaba Cloud ECI via ESS refresh"
author: "Mentra"

inputs:
  environment:
    description: 'Deployment environment (e.g., dev, staging, prod)'
    required: true
  alibaba-access-key-id:
    required: true
    sensitive: true
  alibaba-access-key-secret:
    required: true
    sensitive: true
  deployment-region:
    description: 'Deployment region'
    required: true
  app-name:
    description: 'Name of the application'
    required: true
  acr-instance-id:
    description: 'ACR instance ID'
    required: true
  acr-vpc-domain:
    description: 'ACR VPC domain for internal registry access'
    required: true
  acr-public-domain:
    description: 'ACR public domain'
    required: true
  docker-context:
    required: true
  dockerfile:
    required: true
  image-tag:
    description: 'Docker image tag'
    required: true
  min-instances:
    description: 'Minimum number of instances for auto-scaling'
    required: true
    default: '1'
  max-instances:
    description: 'Maximum number of instances for auto-scaling'
    required: true
    default: '2'
  use-specs:
    description: 'Instance specifications (CPU-Memory)'
    required: true
    default: '2.0-4.0Gi'
  vswitch:
    description: 'Comma-separated list of vSwitch IDs for the ECI instances'
    required: true
  security-group:
    description: 'Security group ID for the ECI instances'
    required: true
  env-yaml:
    description: 'Environment variables in YAML format'
    required: false
    sensitive: true

runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "IMAGE_REPOSITORY_PUBLIC_URL=${{ inputs.acr-public-domain }}/${{ inputs.environment }}/${{ inputs.app-name }}" >> $GITHUB_ENV
        echo "IMAGE_REPOSITORY_VPC_URL=${{ inputs.acr-vpc-domain }}/${{ inputs.environment }}/${{ inputs.app-name }}" >> $GITHUB_ENV
        echo "CONTAINER_GROUP_NAME=mentraos-${{ inputs.environment }}-${{ inputs.app-name }}-cg" >> $GITHUB_ENV
        echo "CONTAINER_NAME=mentraos-${{ inputs.environment }}-${{ inputs.app-name }}-eci" >> $GITHUB_ENV
        echo "SCALING_CONFIGURATION_NAME=mentraos-${{ inputs.environment }}-${{ inputs.app-name }}-scalingConfiguration" >> $GITHUB_ENV

    - name: Install Alibaba CLI
      run: |
        curl -sSL https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz | tar -xz
        sudo mv aliyun /usr/local/bin/
      shell: bash

    - name: Configure Alibaba CLI
      run: |
        aliyun configure set \
          --profile default \
          --mode AK \
          --region ${{ inputs.deployment-region }} \
          --access-key-id ${{ inputs.alibaba-access-key-id }} \
          --access-key-secret ${{ inputs.alibaba-access-key-secret }}
      shell: bash

    - name: Get ACR token
      id: acr-token
      run: |
        TOKEN=$(aliyun cr GetAuthorizationToken \
          --InstanceId ${{ inputs.acr-instance-id }} \
          --RegionId ${{ inputs.deployment-region }} \
        | jq -r '.AuthorizationToken')

        echo "token=$TOKEN" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Docker login
      run: |
        docker login \
          --username cr_temp_user \
          --password ${{ steps.acr-token.outputs.token }} \
          ${{ inputs.acr-public-domain }}
      shell: bash

    # - name: Build & Push Image
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: ${{ inputs.docker-context }}
    #     file: ${{ inputs.dockerfile }}
    #     push: true
    #     tags: |
    #       ${{ env.IMAGE_REPOSITORY_PUBLIC_URL }}:${{ inputs.image-tag }}
    #       ${{ env.IMAGE_REPOSITORY_PUBLIC_URL }}:latest

    # read this from the template.yml file
    - name: Render Deployment Config
      run: |
        envsubst < ${{ github.action_path }}/template.yml > pre_autoscaling.yml
      shell: bash
      env:
        MAX_INSTANCES: ${{ inputs.max-instances }}
        MIN_INSTANCES: ${{ inputs.min-instances }}
        USE_SPECS: ${{ inputs.use-specs }}
        VSWITCH: ${{ inputs.vswitch }}
        SECURITY_GROUP: ${{ inputs.security-group }}
        CONTAINER_GROUP_NAME: ${{ env.CONTAINER_GROUP_NAME }}
        CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
        SCALING_CONFIGURATION_NAME: ${{ env.SCALING_CONFIGURATION_NAME }}

    - name: Debug - Show pre_autoscaling.yml
      run: |
        echo "=== pre_autoscaling.yml content ==="
        cat pre_autoscaling.yml
        echo "\n=================================="
      shell: bash

    - name: Write env YAML
      run: echo "${{ inputs.env-yaml }}" > env.yml
      shell: bash
      
    - name: Debug - Show env.yml
      run: |
        echo "=== env.yml content ==="
        cat env.yml
        echo "\n========================"
      shell: bash

    - name: Apply variable substitution
      run: |
        envsubst < pre_autoscaling.yml > final.yml
      shell: bash
        
    - name: Debug - Show final.yml before env injection
      run: |
        echo "=== final.yml before env injection ==="
        cat final.yml
        echo "\n===================================="
      shell: bash

    - name: Inject env list without knowing indent
      run: |
        yq eval -i '.spec.template.spec.containers[0].env = load("env.yml")' final.yml
      shell: bash

    - name: Debug - Show final.yml after env injection
      run: |
        echo "=== final.yml after env injection ==="
        cat final.yml
        echo "\n===================================="
      shell: bash

    - name: Deploy to ESS
      run: |
        bash "${{ github.action_path }}/scripts/deploy.sh" \
          "${{ env.CONTAINER_GROUP_NAME }}" \
          "${{ inputs.deployment-region }}"
      shell: bash
